apiVersion: apps/v1
kind: Deployment
metadata:
  name: followservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followservice
  template:
    metadata:
      labels:
        app: followservice
    spec:
      containers:
        - name: followservice
          image: zakaria469980/followservice:latest
          ports:
            - containerPort: 5117
---
apiVersion: v1
kind: Service
metadata:
  name: follow-service
spec:
  selector:
    app: followservice  # Adjusted to match the correct label
  ports:
    - protocol: TCP
      port: 5117
      targetPort: 80
      name: http-port
    - protocol: TCP
      port: 7117
      targetPort: 443
      name: https-port
    - name: postgres 
      protocol: TCP
      port: 5434
      targetPort: 5434
  type: ClusterIP