apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-follow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followservice
  template:
    metadata:
      labels:
        app: followservice
    spec:
      containers:
        - name: postgres-follow
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5434
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-follow
spec:
  selector:
    app: followservice
  ports:
    - protocol: TCP
      port: 5434
      targetPort: 5432
